### ISSUE TITLE
NPE in Antlr4RailroadTransformer

### ISSUE THREAD

**Issue by kthoms** [antlr4ide/antlr4ide#187]
The following error has been reported to Eclipse Automated Error Reporting:

```
Bundle: org.eclipse.ui.workbench 3.108.3.v20170216-1539
Message: Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
Exception:
java.lang.IllegalArgumentException: Unhandled parameter types: [null]
    at com.github.jknack.antlr4ide.ui.railroad.trafo.Antlr4RailroadTransformer.toFigure(Antlr4RailroadTransformer.java:443)
    at com.github.jknack.antlr4ide.ui.railroad.trafo.Antlr4RailroadTransformer._toFigure(Antlr4RailroadTransformer.java:88)
    at com.github.jknack.antlr4ide.ui.railroad.trafo.Antlr4RailroadTransformer.toFigure(Antlr4RailroadTransformer.java:381)
    at com.github.jknack.antlr4ide.ui.railroad.trafo.Antlr4RailroadTransformer.transform(Antlr4RailroadTransformer.java:63)
    at com.github.jknack.antlr4ide.ui.railroad.trafo.Antlr4RailroadTransformer.children(Antlr4RailroadTransformer.java:367)
    at com.github.jknack.antlr4ide.ui.railroad.trafo.Antlr4RailroadTransformer._toFigure(Antlr4RailroadTransformer.java:80)
    at com.github.jknack.antlr4ide.ui.railroad.trafo.Antlr4RailroadTransformer.toFigure(Antlr4RailroadTransformer.java:403)
    at com.github.jknack.antlr4ide.ui.railroad.trafo.Antlr4RailroadTransformer.transform(Antlr4RailroadTransformer.java:63)
    at com.github.jknack.antlr4ide.ui.railroad.RailroadSynchronizer.createFigure(RailroadSynchronizer.java:93)
    at com.github.jknack.antlr4ide.ui.railroad.RailroadSynchronizer.access$0(RailroadSynchronizer.java:89)
    at com.github.jknack.antlr4ide.ui.railroad.RailroadSynchronizer$1.exec(RailroadSynchronizer.java:74)
    at com.github.jknack.antlr4ide.ui.railroad.RailroadSynchronizer$1.exec(RailroadSynchronizer.java:1)
    at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
    at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:520)
    at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:492)
    at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:133)
    at com.github.jknack.antlr4ide.ui.railroad.RailroadSynchronizer.partActivated(RailroadSynchronizer.java:71)
    at org.eclipse.ui.internal.PartService$1.run(PartService.java:84)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.PartService.partActivated(PartService.java:81)
    at org.eclipse.ui.internal.WorkbenchWindow$WWinPartService.partActivated(WorkbenchWindow.java:3002)
    at org.eclipse.ui.internal.WorkbenchPage$14.run(WorkbenchPage.java:4977)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.WorkbenchPage.firePartActivated(WorkbenchPage.java:4974)
    at org.eclipse.ui.internal.WorkbenchPage.access$19(WorkbenchPage.java:4962)
    at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage.java:210)
    at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$3.run(PartServiceImpl.java:250)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.firePartActivated(PartServiceImpl.java:247)
    at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:757)
    at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:682)
    at org.eclipse.e4.ui.internal.workbench.swt.AbstractPartRenderer.activate(AbstractPartRenderer.java:95)
    at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer$1.handleEvent(ContributedPartRenderer.java:63)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1366)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1349)
    at org.eclipse.swt.widgets.Shell.setActiveControl(Shell.java:1826)
    at org.eclipse.swt.widgets.Shell.setActiveControl(Shell.java:1789)
    at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:4081)
    at org.eclipse.swt.widgets.Control.gtk_event_after(Control.java:3341)
    at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1986)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:5827)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:5498)
    at org.eclipse.swt.internal.gtk.OS._gtk_widget_grab_focus(OS.java:-2)
    at org.eclipse.swt.internal.gtk.OS.gtk_widget_grab_focus(OS.java:14639)
    at org.eclipse.swt.widgets.Control.forceFocus(Control.java:2636)
    at org.eclipse.swt.widgets.Composite.forceFocus(Composite.java:595)
    at org.eclipse.swt.widgets.Control.forceFocus(Control.java:2629)
    at org.eclipse.swt.widgets.Control.setFocus(Control.java:4619)
    at org.eclipse.swt.widgets.Composite.setFocus(Composite.java:1543)
    at org.eclipse.ui.texteditor.AbstractTextEditor.setFocus(AbstractTextEditor.java:6191)
    at org.eclipse.ui.texteditor.StatusTextEditor.setFocus(StatusTextEditor.java:120)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.delegateSetFocus(CompatibilityPart.java:203)
    at sun.reflect.GeneratedMethodAccessor58.invoke(null:-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:282)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:288)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:259)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:107)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.focusGui(PartRenderingEngine.java:779)
    at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer$2.setFocus(ContributedPartRenderer.java:102)
    at org.eclipse.swt.custom.CTabItem.setFocus(CTabItem.java:332)
    at org.eclipse.swt.custom.CTabFolder.setFocus(CTabFolder.java:2611)
    at org.eclipse.swt.widgets.Control.fixFocus(Control.java:217)
    at org.eclipse.swt.widgets.Control.setVisible(Control.java:5153)
    at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3155)
    at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3163)
    at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1850)
    at org.eclipse.swt.custom.CTabFolder$1.handleEvent(CTabFolder.java:333)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

EXECUTION ENVIRONMENT
Bundles:	
NAME
VERSION
org.eclipse.core.databinding.observable
1.6.0.v20160511-1747
org.eclipse.core.databinding
1.6.0.v20160412-0910
org.eclipse.core.runtime
3.12.0.v20160606-1342
org.eclipse.e4.core.contexts
1.5.1.v20170203-1100
org.eclipse.e4.core.di
1.6.1.v20160712-0927
org.eclipse.e4.ui.workbench
1.4.0.v20160517-1624
org.eclipse.e4.ui.workbench.renderers.swt
0.14.1.v20170117-1415
org.eclipse.e4.ui.workbench.swt
0.14.1.v20160829-0832
org.eclipse.equinox.app
1.3.400.v20150715-1528
org.eclipse.equinox.launcher
1.3.201.v20161025-1711
org.eclipse.swt
3.105.3.v20170228-0512
org.eclipse.ui
3.108.1.v20160929-1045
org.eclipse.ui.ide.application
1.1.101.v20160829-0827
org.eclipse.ui.ide
3.12.3.v20170119-0935
org.eclipse.xtext
2.12.0.v20170518-0959
org.eclipse.xtext.ui
2.12.0.v20170519-0809
Product:	

org.eclipse.epp.package.jee.product_4.6.3.M20170301-0400
Java Runtime:	

1.8.0_121-b13
Operating System:	

Internal Reference: https://dev.eclipse.org/recommenders/committers/aeri/v2/#!/incidents/597f0923e4b05728f8e899f8

**Comment by timeraider4u** [comment]
Thank you for reporting this issue and taking the time to forward it to the ANTLR4IDE project. Unfortunately, I am sorry to say that I believe that this bug will not be fixed in the near future as this project is lacking contributors. I will leave it open for now...

**Comment by timeraider4u** [comment]
By the way: When I try to open the link provided under the point internal reference I either get "404 – Page Not Found" or "You do not have access to this view: /incidents/597f0923e4b05728f8e899f8". I suppose the second one is due to saving privacy of Eclipse.

**Comment by kthoms** [comment]
The link is internal, you can't access it. Take it just as a reference. Mainly it contains the information from above.

You can leave the bug open, but I opened this one to close the issue reported to Eclipse as a 3rd party issue.

**Comment by timeraider4u** [comment]
Okay, thanks!
