### ISSUE TITLE
Errors with simple imports using candidate antlr 4.5

### ISSUE THREAD

**Issue by ericvergnaud** [antlr4ide/antlr4ide#99]
I’m encountering a bug in the IDE with the release candidate which I struggle to understand.
The bug occurs with grammar imports and throws an exception, making the IDE unusable for grammars with imports.

The thrown exception looks as follows:

!ENTRY org.eclipse.core.jobs 4 2 2015-01-09 01:28:41.239
!MESSAGE An internal error occurred during: "Generating Importer.g4".
!STACK 0
java.lang.NullPointerException
    at com.github.jknack.antlr4ide.ui.services.DefaultGrammarResource.fileFrom(DefaultGrammarResource.java:52)
    at com.github.jknack.antlr4ide.ui.services.DefaultGrammarResource.fileFrom(DefaultGrammarResource.java:62)
    at com.github.jknack.antlr4ide.generator.ToolRunner$1.apply(ToolRunner.java:92)
    at com.github.jknack.antlr4ide.generator.ToolRunner$1.apply(ToolRunner.java:1)
    at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:41)
    at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
    at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
    at com.google.common.collect.Iterators.addAll(Iterators.java:357)
    at com.google.common.collect.Iterables.addAll(Iterables.java:351)
    at com.google.common.collect.Sets.newLinkedHashSet(Sets.java:328)
    at org.eclipse.xtext.xbase.lib.IterableExtensions.toSet(IterableExtensions.java:572)
    at com.github.jknack.antlr4ide.generator.ToolRunner.run(ToolRunner.java:97)
    at com.github.jknack.antlr4ide.generator.Antlr4Generator.doGenerate(Antlr4Generator.java:132)
    at com.github.jknack.antlr4ide.generator.Antlr4Generator.access$0(Antlr4Generator.java:120)
    at com.github.jknack.antlr4ide.generator.Antlr4Generator$1.apply(Antlr4Generator.java:104)
    at com.github.jknack.antlr4ide.generator.Antlr4Generator$1.apply(Antlr4Generator.java:1)
    at com.github.jknack.antlr4ide.generator.Jobs$1.run(Jobs.java:33)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

Debugging your code, this seems to occur at the following location: ToolRunner.xtend, line 59

```
// set -lib when is empty
val lib = options.libDirectory
if (lib == null || lib.empty) {
  val grammar = grammarResource.grammarFrom(file)
  val libs = grammar.imports.map[
    grammarResource.fileFrom(it.importURI).parent
  ].toSet
  if (libs.size > 0) {
    options.libDirectory = libs.iterator.next.location.toOSString
  }
}
```

Basically, when trying to locate the parent dir of an imported grammar, grammarResource.fileFrom receives a grammar URI,
and later the following code:

  override fileFrom(Grammar grammar) {
    fileFrom(grammar.eResource)
  }

fails to find a resource. The NullPointerException is raised when calling resource.URI as below.

 override fileFrom(Resource resource) {
    val uri = resource.URI
    workspaceRoot.getFile(new Path(uri.toPlatformString(true)))
  }

The above bug occurs when generating a recognizer using « Run as… », but also affects the editor - see enclosed screen shot.

The bug can be reproduced with a grammar as simple as the enclosed:

Now what puzzles me is the following:
- the bug seems to appear only after the tool has been launched (initial display of the grammar does not highlight any error)
- the bug only occurs with the candidate 4.5 tool (enclosed), when it seems that the exception above occurs in XText related code (grammar with a null eResource). But that’s consistent with the above
- more strangely, if I switch to 4.4, not only does the bug not appear, but when I switch back to 4.5 it doesn’t appear anymore, as if once the java files are generated, all works fine

I’m reluctant to ship 4.5 with such a bug, o would gladly use your help to understand what’s broken in the tool.

This could relate to #713 https://github.com/antlr/antlr4/pull/713, but I don’t see how, since the IDE seems to break before even calling the antlr tool...

Eric

**Comment by ericvergnaud** [comment]
Hi,

narrowing down the issue, I found a scenario which produces the same bug with antlr 4.4, meaning this is not 4.5 specific.

Step1: generate a tool for file Importer.g4
Step 2: using the Launch Group feature (which comes with the C++ toolkit), create a launch group, add the tool created in step 1
Step 3: rename file Importer.g4 to XImporter.g4 (making the tool created in Step 1 invalid)
Step 4: run the tool created in step 2 -> error

In brief, the bug occurs when a tool is launched on a missing resource (not sure if this is possible outside a launch group). The invalid tool (missing resource) is not detected by antlride, and leads to a crash.

The reason I use a launch group is because I generate from the same grammar 5 language targets. My project comprises 12 grammar files, I recently renamed one of those grammars and one of the tools was not updated properly.

Since I fixed the tool, the problem disappeared.

You might argue that this is a Launch group bug rather than an antlride one. I'l leave it to you whether or not to protect your code from launches of invalid tools :-)

Cheers

**Comment by jknack** [comment]
glad you figure it out. I will look later and see if I can do something.

**Comment by HSorensen** [comment]
Can you share the grammars that cause this problem?

**Comment by HSorensen** [comment]
I think this is not an antlr4ide bug. Will close unless I hear otherwise.
